#! /usr/bin/env python3
# encoding: utf-8

pysoy = bld(
  features     = 'c cshlib pyext',
  target       = 'soy',
  uselib       = ['SOY'],
  includes     = '../include',
  cflags       = ['-g'],
  source       = bld.path.ant_glob('**/*.c')
)

